language: python
python:
  - '3.6'
  - '3.7'
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  # install in batch mode i.e. no input
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  # clear bash cache table
  - hash -r
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib basemap shapely nose netcdf4 cftime coverage coveralls pycurl pyproj seaborn simplejson sqlite statsmodels libgdal gdal configparser cartopy affine tqdm xarray gxx_linux-64 pthread-stubs imageio
  - source activate test-env
branches:
  except:
    - config
    - notebooks
script:
  - python installer/setup.py build_ext -i
  - nosetests -v --with-coverage --cover-package=.
after_success: coveralls
notifications:
  slack:
    secure: Ckmwy59ytS1GPRZ5Tmvzad6+W9AzvfjNJAa4orgdKS/WktoK4b9W2rbTHxi8V3hBLIDUCso8vIQi3rVXpWY3cFMvb/uRbXO4GiIW1iua3CKjxd+dEw4E6/8DEknS1qdGJRDhN9/3ucZNvSGHY3EQQDfxb/R+OGd2jT6+jed8pss=
