name: Pylint tests for TCRM 

on: 
  push:
    branches:  [ master, develop ]

jobs:
  build:
    name: Pylint TCRM
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python env
      uses: conda-incubator/setup-miniconda@v2.0.0
      with: 
        activate-environment: tcrm
        environment-file: tcrmenv.yml
        python-version: 3.7
        auto-activate-base: false
        
    - name: Install dependencies
      run: |
        conda install pylint
    - name: Analysing the code with pylint
      run: which pylint
      run: pylint `find . -name "*.py" | xargs`
 
